
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/habitdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: yourusername
    password: yourpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
